services:
    app:
        build: .
        ports:
            - "8000:80"
#        volumes:
#            - .:/var/www/html
        depends_on:
            - redis
            - postgres
        env_file:
            -   .env
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - REDIS_HOST=redis
        command: >
            bash -c "
            while ! nc -z postgres 5432; do
              echo 'Waiting for PostgreSQL...';
              sleep 1;
            done;
            php artisan migrate --force;
            apache2-foreground
            "

    postgres:
        image: postgres:15
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    redis:
        image: redis:7
        ports:
            - "6379:6379"

volumes:
    postgres_data:
